### PR TITLE
Ground seg

### PR DESCRIPTION
**Pull request by kaicao233**
Main functionalities should be completed.

Remaining limitations:

- Collision detection not working when too close to obstacles
- Changing from spine_offset=0.3 to -0.3 causes too large (unpredicatable) a pose change
- Tilted horizon can cause false decisions

### CODE REVIEW

**Comment by Yamada-Yoshifumi** [comment]
Looks good

**Comment by Yamada-Yoshifumi** [comment]
looks good

**Comment by jl-wang6** [comment]
LGTM :)

**Comment by jl-wang6** [comment]
LGTM :)

**Pull request merged**
